name: Generate Snake

on:
  schedule:
    - cron: '0 0 * * *' # Runs daily at midnight
  push:
    branches:
      - main

jobs:
  snake:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Generate Snake
      uses: Platane/snk@v2
      with:
        github_user_name: ${{ github.repository_owner }}
        output: github-contribution-grid-snake.svg
    - name: Commit and push snake animation
      uses: EndBug/add-and-commit@v7
      with:
        add: github-contribution-grid-snake.svg
        message: "Update snake animation"
